[package]
name = "forest_2"
version = "0.1.0"
authors = ["boris"]

[dependencies]
rand = "0.5.0"
time = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
num_cpus = "1.8.0"
smallvec = "0.6.1"
ndarray = "0.12"
ndarray-linalg = { version = "0.10" }
openblas-src = { version = "0.5" , features = ["system"] }
